# Site settings
title: Bioschemas
email: contact@bioschemas.org
description: > # this means to ignore newlines until "baseurl:"
  Bioschemas relies and extends from schema.org and aims to reuse existing
  standards and reach consensus among a wide number of life sciences organizations and communities.
url: "http://bioschemas.org" # the base hostname & protocol for your site
twitter_username: Bioschemas
github_username: Bioschemas

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-relative-links

# Collections
collections_dir: pages
collections:
  properties:
    output: true
    permalink: /:collection/:path
  types:
    output: true
    permalink: /:collection/:path
  meetings:
    output: true
    permalink: /:collection/:path
  tutorials:
    output: true
    permalink: /:collection/:path
  people:
    output: true
    permalink: /:collection/:path
  groups:
    output: true
    permalink: /:collection/:path
  useCases:
    output: true
    permalink: /:collection/:path
  stories:
    output: true
    permalink: /:collection/:path
  profiles:
    output: true
    permalink: /:collection/:path
  community:
    output: true
    permalink: /:collection/:path
  about:
    output: true
    permalink: /:collection/:path
  news:
    output: true
    permalink: /:collection/:path
  developer:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      permalink: /:basename
      layout: "default"
  - scope:
      path: ""
      type: "types"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "properties"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "profiles"
    values:
      layout: "profiles"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
