# Site settings
title: Bioschemas
email: contact@bioschemas.org
description: > # this means to ignore newlines until "baseurl:"
  Bioschemas relies and extends from schema.org and aims to reuse existing
  standards and reach consensus among a wide number of life sciences organizations and communities.
url: "http://bioschemas.org" # the base hostname & protocol for your site
twitter_username: Bioschemas
github_username:  Bioschemas

permalink: pretty

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed
highlighter: rouge
plugins:
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-relative-links

# Collections
collections_dir: pages
collections:
  types:
    output: true

  meetings:
    output: true

  tutorials:
    output: true

  people:
    output: true

  groups:
    output: true

  useCases:
    output: true

  stories:
    output: true

  profiles:
    output: true

  community:
    output: true

  about:
    output: true

  news:
    output: true

  developer:
    output: true


# Defaults
defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "types"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "profiles"
    values:
      layout: "profiles"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
