# Site settings
title: Bioschemas
email: contact@bioschemas.org
description: > # this means to ignore newlines until "baseurl:"
  Bioschemas relies and extends from schema.org and aims to reuse existing
  standards and reach consensus among a wide number of life sciences organizations and communities.
url: "http://bioschemas.org" # the base hostname & protocol for your site
twitter_username: Bioschemas
github_username:  Bioschemas
permalink: /news/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed
highlighter: rouge
plugins:
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-relative-links


# Collections
collections_dir: pages
collections:
  types:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  meetings:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  tutorials:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  people:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  groups:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  useCases:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  stories:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  profiles:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  community:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  about:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  news:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "profiles"
    values:
      layout: "profiles"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "types"
    values:
      layout: "default"