# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bioschemas
email: contact@bioschemas.org
description: > # this means to ignore newlines until "baseurl:"
  Bioschemas relies and extends from schema.org and aims to reuse existing
  standards and reach consensus among a wide number of life sciences organizations and communities.
url: "http://bioschemas.org" # the base hostname & protocol for your site
twitter_username: Bioschemas
github_username:  Bioschemas
permalink: /news/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown

plugins:
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-relative-links

sass:
  sass_dir: assets/css
  style: compressed

# Collections
collections_dir: pages
collections:
  types:
    output: true
    permalink: /:collection/:path
  meetings:
    output: true
    permalink: /:collection/:path
  tutorials:
    output: true
    permalink: /:collection/:path
  people:
    output: true
    permalink: /:collection/:path
  groups:
    output: true
    permalink: /:collection/:path
  useCases:
    output: true
    permalink: /:collection/:path
  stories:
    output: true
    permalink: /:collection/:path
  profiles:
    output: true
    permalink: /:collection/:path
  community:
    output: true
    permalink: /:collection/:path
  publications:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: "profiles"
    values:
      layout: "profiles"
  - scope:
      path: ""
      type: "types"
    values:
      layout: "default"