# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bioschemas
email: contact@bioschemas.org
description: > # this means to ignore newlines until "baseurl:"
  Bioschemas relies and extends from schema.org and aims to reuse existing
  standards and reach consensus among a wide number of life sciences organizations and communities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bioschemas.org" # the base hostname & protocol for your site
twitter_username: Bioschemas
github_username:  Bioschemas
permalink: /news/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown

plugins:
 - jekyll-redirect-from
 - jekyll-sitemap

# Collections
collections:
  specifications:
    output: true
    permalink: /:collection/:path/
#  devSpecs:
#    output: true
#    permalink: /specifications/drafts/:path/
  types:
    output: true
    permalink: /:collection/:path/
#  devTypes:
#    output: true
#    permalink: /types/drafts/:path/
  meetings:
    output: true
    permalink: /:collection/:path/ #Note, trailing / needed to avoid .html
  people:
    output: true
    permalink: /:collection/:path/
  groups:
    output: true
    permalink: /:collection/:path/
  useCases:
    output: true
    permalink: /:collection/:path/
  liveDeploys:
    output: true
    permalink: /:collection/:path/
  stories:
    output: true
  profiles:
    output: true
    permalink: /:collection/:path/
