name: validate-live-deploys
on: [push]
jobs:
  json-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g ajv-cli
      - run: npm install -g ajv-formats
      - run: ajv -c ajv-formats -s _data/live_deployments_schema.json -d _data/live_deployments.json
